### ISSUE TITLE
Linking native executables on Windows

### ISSUE THREAD

**Issue by kkirstein** [def-lkb/stb_image#2]
In your Makefile you have the follwoing rule:
```
stb_image.cmxa stb_image$(EXT_LIB): stb_image.cmx dll_stb_image_stubs$(EXT_DLL)
	$(OCAMLOPT) -package result -a -o $@ $< \
	      -cclib -l_stb_image_stubs \
	      -ccopt -O3 -ccopt -std=gnu99 -ccopt -ffast-math
```

When I build an executable containing stb_image with `ocamlbuild` it looks like that the C-compiler flags above are also used for linking stb_image to my executable (This is just a guess, I'm no ocamlbuild expert). The involved linker on Windows (`flexlink`) complains about unknown options like `-O3` and fails (I suspect gcc/ld would handle this correctly).
When looking at the log during building of stb_image, it looks like the Makefile rule above is only used to build `stb_image.cmxa` from `stb_image.cmx`, so there are no C-compiler flags needed (At least to my knowledge, but I'm a OCaml newbie).
When I omit the `-ccopt` switches in the rule above, linking of my executable works.
Do I miss something here?

**Comment by let-def** [comment]
You are correct. It is wrong to pass the flags here.
If you submit a PR I will merge it, otherwise I can fix that tomorrow.
